export const PERMISOS = Object.freeze({
  VER_CONSULTAS_POR_FILTRO: 'VER_CONSULTAS_POR_FILTRO',
  VER_DASHBOARD: 'VER_DASHBOARD',
  REGISTRAR_USUARIOS: 'REGISTRAR_USUARIOS',
  VER_HISTORIAL: 'VER_HISTORIAL',
  EXPLORAR_PROSPECTOS: 'EXPLORAR_PROSPECTOS',
  PROB_ADQUISICION_PRODUCTO: 'PROB_ADQUISICION_PRODUCTO',
  INTERPRETACION_PROB: 'INTERPRETACION_PROB',
  RECOMENDACION_SUGERIDA: 'RECOMENDACION_SUGERIDA',
  DEFINIR_VALORES_PARAMETRICOS: 'DEFINIR_VALORES_PARAMETRICOS',
  ANALISIS_VALORES_INFLUYENTES: 'ANALISIS_VALORES_INFLUYENTES',
  SIMULACION_ESCENARIOS: 'SIMULACION_ESCENARIOS',
});
